# Generated by Django 3.2.16 on 2024-09-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_htbmpw', upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
