# Generated by Django 3.2.16 on 2024-09-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20240908_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='image_filter',
            field=models.CharField(choices=[('fun', 'Fun'), ('food', 'Food'), ('nature', 'Nature'), ('health', 'Health'), ('pet', 'Pet'), ('cat', 'Cat'), ('dog', 'Dog'), ('bird', 'Bird'), ('2024', '2024')], default='Pet', max_length=32),
        ),
    ]
