# Generated by Django 3.2.16 on 2024-09-09 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
